import assert from "node:assert/strict";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import test from "node:test";
import { pathToFileURL } from "node:url";
import type { Logger } from "pino";
import { parseGolangciLintJson } from "../src/cli-parsers.js";
import { DiagnosticsStore } from "../src/diagnostics.js";
import { LspProvider } from "../src/provider-lsp.js";
import type { BridgeLifecycleConfig, ProviderSpec } from "../src/types.js";

function withWorkspace(fn: (workspaceRoot: string) => void): void {
	const workspaceRoot = mkdtempSync(join(tmpdir(), "pi-lsp-bridge-generated-"));
	try {
		fn(workspaceRoot);
	} finally {
		rmSync(workspaceRoot, { recursive: true, force: true });
	}
}

function writeWorkspaceFile(workspaceRoot: string, relativePath: string, content: string): string {
	const filePath = join(workspaceRoot, relativePath);
	mkdirSync(dirname(filePath), { recursive: true });
	writeFileSync(filePath, content, "utf8");
	return filePath;
}

const lifecycle: BridgeLifecycleConfig = {
	lspDebounceMs: 10,
	cliDebounceMs: 10,
	cliWorkspaceDebounceMs: 10,
	injectCooldownMs: 10,
	idleSuspendMs: 10,
	triggerCooldownMs: 10,
	maxOpenDocuments: 8,
	maxFileBytes: 128_000,
	bootstrapSampleFiles: 4,
	orphanSweepMaxAgeMs: 10,
};

const logger = {
	debug() {},
	warn() {},
} as unknown as Logger;

const cleanupRegistry = {
	register() {},
	unregister() {},
};

const lspSpec: ProviderSpec = {
	id: "gopls",
	kind: "lsp",
	role: "primary",
	priority: 1,
	commandCandidates: [],
	selectors: [{ languageId: "go", extensions: [".go"] }],
};

test("parseGolangciLintJson ignores diagnostics from generated files", () => {
	withWorkspace((workspaceRoot) => {
		const relativePath = "ports/mocks/mock_tmux_control_port.go";
		const filePath = writeWorkspaceFile(
			workspaceRoot,
			relativePath,
			"// Code generated by mockery v2.53.0. DO NOT EDIT.\npackage mocks\n",
		);
		const payload = JSON.stringify({
			Issues: [
				{
					FromLinter: "gocritic",
					Text: "interface{} can be replaced by any",
					Pos: { Filename: filePath, Line: 12, Column: 3 },
				},
			],
		});

		const diagnostics = parseGolangciLintJson("golangci-lint", workspaceRoot, payload);

		assert.equal(diagnostics.length, 0);
	});
});

test("parseGolangciLintJson keeps diagnostics for non-generated files", () => {
	withWorkspace((workspaceRoot) => {
		const relativePath = "pkg/service/service.go";
		const filePath = writeWorkspaceFile(workspaceRoot, relativePath, "package service\n");
		const payload = JSON.stringify({
			Issues: [
				{
					FromLinter: "gocritic",
					Text: "interface{} can be replaced by any",
					Pos: { Filename: filePath, Line: 4, Column: 2 },
				},
			],
		});

		const diagnostics = parseGolangciLintJson("golangci-lint", workspaceRoot, payload);

		assert.equal(diagnostics.length, 1);
		assert.equal(diagnostics[0]?.filePath, relativePath);
	});
});

test("LspProvider ignores diagnostics from generated files", () => {
	withWorkspace((workspaceRoot) => {
		const relativePath = "ports/mocks/mock_tmux_control_port.go";
		const filePath = writeWorkspaceFile(
			workspaceRoot,
			relativePath,
			"// Code generated by MockGen. DO NOT EDIT.\npackage mocks\n",
		);
		const store = new DiagnosticsStore();
		const provider = new LspProvider(lspSpec, workspaceRoot, [relativePath], store, lifecycle, cleanupRegistry, () => {}, logger);

		(provider as any).handleMessage({
			method: "textDocument/publishDiagnostics",
			params: {
				uri: pathToFileURL(filePath).toString(),
				diagnostics: [
					{
						severity: 1,
						message: "generated file diagnostic",
						range: {
							start: { line: 0, character: 0 },
							end: { line: 0, character: 10 },
						},
					},
				],
			},
		});

		assert.equal(store.getAll().length, 0);
	});
});
