import type { FileSelector, ProviderSpec } from "./types.js";

const jsTsSelectors: FileSelector[] = [
	{ languageId: "typescript", extensions: [".ts", ".tsx", ".mts", ".cts"] },
	{ languageId: "javascript", extensions: [".js", ".jsx", ".mjs", ".cjs"] },
];

export const DEFAULT_PROVIDER_SPECS: ProviderSpec[] = [
	{
		id: "typescript-language-server",
		kind: "lsp",
		role: "primary",
		family: "javascript-typescript",
		priority: 100,
		description: "TypeScript/JavaScript LSP",
		detect: {
			repoFilesAny: ["package.json", "tsconfig.json", "jsconfig.json", "deno.json", "deno.jsonc"],
			fileExtensionsAny: [".ts", ".tsx", ".mts", ".cts", ".js", ".jsx", ".mjs", ".cjs"],
			packageJsonDepsAny: ["typescript", "typescript-language-server", "eslint", "vite", "next", "astro", "svelte"],
		},
		selectors: jsTsSelectors,
		rootMarkers: ["tsconfig.json", "jsconfig.json", "package.json"],
		commandCandidates: [
			{ command: "typescript-language-server", args: ["--stdio"] },
			{ command: "vtsls", args: ["--stdio"] },
		],
	},
	{
		id: "eslint",
		kind: "cli",
		role: "supplemental",
		family: "javascript-typescript",
		priority: 200,
		description: "ESLint CLI diagnostics",
		detect: {
			configFilesAny: [
				"eslint.config.js",
				"eslint.config.cjs",
				"eslint.config.mjs",
				"eslint.config.ts",
				".eslintrc",
				".eslintrc.json",
				".eslintrc.js",
				".eslintrc.cjs",
				".eslintrc.yaml",
				".eslintrc.yml",
			],
			fileExtensionsAny: [".ts", ".tsx", ".mts", ".cts", ".js", ".jsx", ".mjs", ".cjs"],
		},
		selectors: jsTsSelectors,
		configMarkers: [
			"eslint.config.js",
			"eslint.config.cjs",
			"eslint.config.mjs",
			"eslint.config.ts",
			".eslintrc",
			".eslintrc.json",
			".eslintrc.js",
			".eslintrc.cjs",
			".eslintrc.yaml",
			".eslintrc.yml",
		],
		commandCandidates: [{ command: "eslint", args: ["--format", "json"] }],
		cli: {
			parser: "eslint-json",
			mode: "files",
			runOnStartup: false,
			runOnChange: true,
		},
	},
	{
		id: "gopls",
		kind: "lsp",
		role: "primary",
		family: "go",
		priority: 100,
		description: "Go LSP",
		detect: {
			repoFilesAny: ["go.mod", "go.work"],
			fileExtensionsAny: [".go"],
		},
		selectors: [{ languageId: "go", extensions: [".go"] }],
		rootMarkers: ["go.work", "go.mod"],
		commandCandidates: [{ command: "gopls", args: [] }],
	},
	{
		id: "golangci-lint",
		kind: "cli",
		role: "supplemental",
		family: "go",
		priority: 200,
		detect: {
			configFilesAny: [".golangci.yml", ".golangci.yaml", ".golangci.toml", ".golangci.json"],
			fileExtensionsAny: [".go"],
		},
		selectors: [{ languageId: "go", extensions: [".go"] }],
		configMarkers: [".golangci.yml", ".golangci.yaml", ".golangci.toml", ".golangci.json"],
		commandCandidates: [{ command: "golangci-lint", args: ["run", "--out-format", "json"] }],
		cli: {
			parser: "golangci-lint-json",
			mode: "workspace",
			runOnStartup: true,
			runOnChange: true,
		},
	},
	{
		id: "rust-analyzer",
		kind: "lsp",
		role: "primary",
		family: "rust",
		priority: 100,
		description: "Rust LSP",
		detect: {
			repoFilesAny: ["Cargo.toml"],
			fileExtensionsAny: [".rs"],
		},
		selectors: [{ languageId: "rust", extensions: [".rs"] }],
		rootMarkers: ["Cargo.toml"],
		commandCandidates: [{ command: "rust-analyzer", args: [] }],
	},
	{
		id: "pyright",
		kind: "lsp",
		role: "primary",
		family: "python",
		priority: 120,
		description: "Python LSP",
		detect: {
			repoFilesAny: ["pyproject.toml", "setup.py", "setup.cfg", "requirements.txt"],
			fileExtensionsAny: [".py"],
		},
		selectors: [{ languageId: "python", extensions: [".py"] }],
		rootMarkers: ["pyproject.toml", "setup.py", "setup.cfg", "requirements.txt"],
		commandCandidates: [{ command: "pyright-langserver", args: ["--stdio"] }, { command: "pylsp", args: [] }],
	},
	{
		id: "ruff",
		kind: "cli",
		role: "supplemental",
		family: "python",
		priority: 220,
		description: "Ruff CLI diagnostics",
		detect: {
			configFilesAny: ["ruff.toml", ".ruff.toml", "pyproject.toml"],
			fileExtensionsAny: [".py"],
		},
		selectors: [{ languageId: "python", extensions: [".py"] }],
		configMarkers: ["ruff.toml", ".ruff.toml", "pyproject.toml"],
		commandCandidates: [{ command: "ruff", args: ["check", "--output-format", "json"] }],
		cli: {
			parser: "ruff-json",
			mode: "files",
			runOnStartup: false,
			runOnChange: true,
		},
	},
	{
		id: "clangd",
		kind: "lsp",
		role: "primary",
		family: "c-cpp",
		priority: 100,
		description: "C/C++ LSP",
		detect: {
			repoFilesAny: ["compile_commands.json", "compile_flags.txt", "CMakeLists.txt"],
			fileExtensionsAny: [".c", ".cc", ".cpp", ".cxx", ".h", ".hpp", ".hh", ".hxx"],
		},
		selectors: [
			{ languageId: "c", extensions: [".c", ".h"] },
			{ languageId: "cpp", extensions: [".cc", ".cpp", ".cxx", ".hpp", ".hh", ".hxx"] },
		],
		rootMarkers: ["compile_commands.json", "compile_flags.txt", "CMakeLists.txt"],
		commandCandidates: [{ command: "clangd", args: [] }],
	},
	{
		id: "yaml-language-server",
		kind: "lsp",
		role: "primary",
		family: "yaml",
		priority: 100,
		description: "YAML LSP",
		detect: { fileExtensionsAny: [".yaml", ".yml"] },
		selectors: [{ languageId: "yaml", extensions: [".yaml", ".yml"] }],
		commandCandidates: [{ command: "yaml-language-server", args: ["--stdio"] }],
	},
	{
		id: "json-language-server",
		kind: "lsp",
		role: "primary",
		family: "json",
		priority: 100,
		description: "JSON LSP",
		detect: { fileExtensionsAny: [".json", ".jsonc"] },
		selectors: [{ languageId: "json", extensions: [".json", ".jsonc"] }],
		commandCandidates: [{ command: "vscode-json-language-server", args: ["--stdio"] }],
	},
	{
		id: "bash-language-server",
		kind: "lsp",
		role: "primary",
		family: "shell",
		priority: 100,
		description: "Shell LSP",
		detect: {
			repoFilesAny: [".shellcheckrc"],
			fileExtensionsAny: [".sh", ".bash", ".zsh"],
		},
		selectors: [{ languageId: "shellscript", extensions: [".sh", ".bash", ".zsh"] }],
		commandCandidates: [{ command: "bash-language-server", args: ["start"] }],
	},
	{
		id: "html-language-server",
		kind: "lsp",
		role: "primary",
		family: "html",
		priority: 100,
		description: "HTML LSP",
		detect: { fileExtensionsAny: [".html"] },
		selectors: [{ languageId: "html", extensions: [".html"] }],
		commandCandidates: [{ command: "vscode-html-language-server", args: ["--stdio"] }],
	},
	{
		id: "css-language-server",
		kind: "lsp",
		role: "primary",
		family: "css",
		priority: 100,
		description: "CSS LSP",
		detect: { fileExtensionsAny: [".css", ".scss", ".less"] },
		selectors: [{ languageId: "css", extensions: [".css", ".scss", ".less"] }],
		commandCandidates: [{ command: "vscode-css-language-server", args: ["--stdio"] }],
	},
	{
		id: "marksman",
		kind: "lsp",
		role: "primary",
		family: "markdown",
		priority: 100,
		description: "Markdown LSP",
		detect: { fileExtensionsAny: [".md"] },
		selectors: [{ languageId: "markdown", extensions: [".md"] }],
		commandCandidates: [{ command: "marksman", args: ["server"] }, { command: "markdown-language-server", args: ["--stdio"] }],
	},
];

export function findDefaultProviderById(id: string): ProviderSpec | undefined {
	return DEFAULT_PROVIDER_SPECS.find((provider) => provider.id === id);
}

export function findDefaultProviderForLanguageId(languageId: string): ProviderSpec | undefined {
	return DEFAULT_PROVIDER_SPECS.find((provider) => provider.selectors?.some((selector) => selector.languageId === languageId));
}
